// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dd

import (
	"github.com/Akshayvij07/thambola-generator/pkg/api"
	"github.com/Akshayvij07/thambola-generator/pkg/api/handler"
	"github.com/Akshayvij07/thambola-generator/pkg/config"
	"github.com/Akshayvij07/thambola-generator/pkg/db"
	"github.com/Akshayvij07/thambola-generator/pkg/repository"
	"github.com/Akshayvij07/thambola-generator/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	ticketRepository := repository.NewTicketRepository(gormDB)
	ticketUseCase := usecase.NewTicketUseCase(ticketRepository)
	ticketHandler := handler.NewUserHandler(ticketUseCase)
	serverHTTP := http.NewServerHTTP(ticketHandler)
	return serverHTTP, nil
}
